const NewTournamentActionTypes = {
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  SUBMIT_QUANTITY: "SUBMIT_QUANTITY",
  ADD_PLAYERPOOL_ITEM: "ADD_PLAYERPOOL_ITEM",
  REMOVE_PLAYERPOOL_ITEM: "REMOVE_PLAYERPOOL_ITEM",
  ADD_TOURNEYPOOL_ITEM: "ADD_TOURNEYPOOL_ITEM",
  REMOVE_TOURNEYPOOL_ITEM: "REMOVE_TOURNEYPOOL_ITEM",
  UPDATE_PLAYERPOOL_COLLECTION: "UPDATE_PLAYERPOOL_COLLECTION",
  UPDATE_TOURNEYPOOL_COLLECTION: "UPDATE_TOURNEYPOOL_COLLECTION",
  RESET_NEWTOURNEY_REDUCER: "RESET_NEWTOURNEY_REDUCER",
};

export default NewTournamentActionTypes;
